// Host program: precomputes, for each smoke test, the protoacc descriptor
// table + a serialized protobuf input, and emits them as C arrays in a header.
// The bare-metal test then links ONLY accellib (no protobuf): it parses the
// embedded input with the accelerator and re-serializes it, checking the
// round-trip output equals the embedded input.
//
// The descriptor table embeds runtime addresses (entry 0 = default-instance
// vptr; nested-message field entries = pointer to the child descriptor table).
// We zero the vptr (unused by the accelerator round-trip) and emit nested
// pointers as 0 + a runtime patch_descriptors() that wires child tables in.
// All other entries (sizeof, has_bits offset, field offsets, min/max field)
// are layout-derived and portable x86-64 -> riscv64 (both LP64).

#include "primitives.pb.h"
#include <google/protobuf/arena.h>
#include <cstdio>
#include <cstdint>
#include <string>
#include <vector>
#include <map>

using namespace std;

static FILE* out;
static map<const uint64_t*, string> table_names;
static vector<pair<string, const uint64_t*>> emit_order;
static int tbl_counter;

static size_t descr_len(const uint64_t* d) {
    uint64_t e3 = d[3];
    uint32_t minf = (uint32_t)(e3 >> 32);
    uint32_t maxf = (uint32_t)(e3 & 0xffffffffULL);
    size_t nrel = (size_t)(maxf - minf + 1);
    // header(4) + 2 u64 per field + is_submessage bitfield. The serializer reads
    // the is_submessage bits at byte offset 32 + nfields*16 (one 32-bit word per
    // 32 fields, rounded up to u64). Omitting it makes the serializer mis-detect
    // sub-message fields -> SerFieldHandler "not yet implemented" assert.
    size_t sub_u64 = (((nrel + 31) / 32) + 1) / 2;
    return 4 + nrel * 2 + sub_u64;
}

// u64 count of the field-entry region (2 per field); nested pointers and the
// is_submessage bitfield are located relative to this.
static size_t descr_field_words(const uint64_t* d) {
    uint64_t e3 = d[3];
    uint32_t minf = (uint32_t)(e3 >> 32), maxf = (uint32_t)(e3 & 0xffffffffULL);
    return (size_t)(maxf - minf + 1) * 2;
}

// Register a descriptor table (dedup by host pointer) and recurse into the
// nested-message pointers it contains.
static string register_table(const uint64_t* d) {
    auto it = table_names.find(d);
    if (it != table_names.end()) return it->second;
    string name = "descr_" + to_string(tbl_counter++);
    table_names[d] = name;
    size_t fend = 4 + descr_field_words(d);
    for (size_t i = 4; i + 1 < fend; i += 2) {
        const uint64_t* child = (const uint64_t*)d[i + 1];
        if (child) register_table(child);
    }
    emit_order.push_back({name, d});
    return name;
}

static void emit_tables() {
    for (auto& pr : emit_order) {
        const uint64_t* d = pr.second;
        size_t n = descr_len(d);
        size_t fend = 4 + descr_field_words(d);
        // 16-byte aligned: the accelerator reads 128-bit field entries and the
        // TL monitor requires Get addresses aligned to the access size (the
        // original _ACCEL_DESCRIPTORS arrays are declared alignas(16)).
        fprintf(out, "__attribute__((aligned(16))) static uint64_t %s[%zu] = {\n", pr.first.c_str(), n);
        for (size_t i = 0; i < n; i++) {
            uint64_t v = d[i];
            if (i == 0) v = 0;                                       // default-instance vptr (unused)
            else if (i >= 5 && i < fend && ((i - 4) % 2 == 1)) v = 0; // nested ptr -> patched at runtime
            // everything else (incl. the trailing is_submessage bitfield) verbatim
            fprintf(out, "  0x%016llxULL,\n", (unsigned long long)v);
        }
        fprintf(out, "};\n");
    }
    fprintf(out, "static void patch_descriptors(void) {\n");
    for (auto& pr : emit_order) {
        const uint64_t* d = pr.second;
        size_t fend = 4 + descr_field_words(d);
        for (size_t i = 4; i + 1 < fend; i += 2) {
            const uint64_t* child = (const uint64_t*)d[i + 1];
            if (child) {
                fprintf(out, "  %s[%zu] = (uint64_t)(uintptr_t)%s;\n",
                        pr.first.c_str(), i + 1, table_names[child].c_str());
            }
        }
    }
    fprintf(out, "}\n");
}

static void emit_bytes(const char* name, const string& s) {
    fprintf(out, "static const unsigned char %s[] = {", name);
    for (size_t i = 0; i < s.size(); i++) {
        if (i % 16 == 0) fprintf(out, "\n  ");
        fprintf(out, "0x%02x,", (unsigned char)s[i]);
    }
    fprintf(out, "\n};\n");
}

static void start(const char* fname) {
    out = fopen(fname, "w");
    table_names.clear();
    emit_order.clear();
    tbl_counter = 0;
    fprintf(out, "// auto-generated by gen_data.cpp -- do not edit\n");
    fprintf(out, "#include <stdint.h>\n");
}

static void finish(const uint64_t* root, const string& input, const char* testname) {
    string rootname = register_table(root);
    emit_tables();
    emit_bytes("serialized_input", input);
    fprintf(out, "#define ROOT_DESCRIPTOR %s\n", rootname.c_str());
    fprintf(out, "#define SERIALIZED_INPUT_LEN %zuUL\n", input.size());
    fprintf(out, "#define TEST_NAME \"%s\"\n", testname);
    fclose(out);
}

int main() {
    GOOGLE_PROTOBUF_VERIFY_VERSION;
    google::protobuf::Arena arena;
    string s;

    // double (5 scalar double fields)
    {
        start("double_data.h");
        auto* m = google::protobuf::Arena::CreateMessage<primitivetests::PaccdoubleMessage>(&arena);
        m->set_paccdouble_0(1.0); m->set_paccdouble_1(2.0); m->set_paccdouble_2(3.0);
        m->set_paccdouble_3(4.0); m->set_paccdouble_4(5.0);
        s.clear(); m->SerializeToString(&s);
        finish(primitivetests_FriendStruct_PaccdoubleMessage_ACCEL_DESCRIPTORS::PaccdoubleMessage_ACCEL_DESCRIPTORS, s, "double");
    }

    // uint64 (values chosen to need multi-byte varints)
    {
        start("uint64_data.h");
        auto* m = google::protobuf::Arena::CreateMessage<primitivetests::Paccuint64_size05BMessage>(&arena);
        m->set_paccuint64_0(1ULL << 33); m->set_paccuint64_1(1ULL << 34); m->set_paccuint64_2(1ULL << 30);
        m->set_paccuint64_3(12345678ULL); m->set_paccuint64_4(0xdeadbeefULL);
        s.clear(); m->SerializeToString(&s);
        finish(primitivetests_FriendStruct_Paccuint64_size05BMessage_ACCEL_DESCRIPTORS::Paccuint64_size05BMessage_ACCEL_DESCRIPTORS, s, "uint64");
    }

    // string
    {
        start("string_data.h");
        auto* m = google::protobuf::Arena::CreateMessage<primitivetests::PaccstringMessage>(&arena);
        m->set_paccstring_0("hello protoacc baremetal");
        s.clear(); m->SerializeToString(&s);
        finish(primitivetests_FriendStruct_PaccstringMessage_ACCEL_DESCRIPTORS::PaccstringMessage_ACCEL_DESCRIPTORS, s, "string");
    }

    // nested message (PaccPaccdoubleMessageMessage contains a PaccdoubleMessage)
    {
        start("nested_data.h");
        auto* m = google::protobuf::Arena::CreateMessage<primitivetests::PaccPaccdoubleMessageMessage>(&arena);
        auto* inner = m->mutable_paccpaccdoublemessage_0();
        inner->set_paccdouble_0(1.0); inner->set_paccdouble_1(2.0); inner->set_paccdouble_2(3.0);
        inner->set_paccdouble_3(4.0); inner->set_paccdouble_4(5.0);
        s.clear(); m->SerializeToString(&s);
        finish(primitivetests_FriendStruct_PaccPaccdoubleMessageMessage_ACCEL_DESCRIPTORS::PaccPaccdoubleMessageMessage_ACCEL_DESCRIPTORS, s, "nested");
    }

    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}
